<?php

/**
 * Implementation of hook_apachesolr_field_mappings().
 */
function skusearch_apachesolr_field_mappings() {
  $mappings = array(
    'per-field' => array(
      'field_sku' => array(
        'indexing_callback' => 'apachesolr_fields_default_indexing_callback',
        'index_type' => 'text',
        'query_types' => array('term'),
        'query_type' => 'term',
        'multiple' => FALSE,
      ),
    ),
  );
  return $mappings;
}

/**
 * Implementation of hook_apachesolr_query_alter().
 */
function skusearch_apachesolr_query_alter($query) {
  $query->addParam('fl', 'ts_field_sku');

  if ($query->getName() == 'skusearch_autocomplete') {
    $query->removeParam('qf');
    $query->addParam('qf', 'ts_field_sku^40');
  }
}

/**
 * Implementation of hook_menu().
 */
function skusearch_menu() {
  $items['search/sku'] = array(
    'title' => 'Sku Search',
    'page callback' => 'skusearch_query_sku',
    'access callback' => 'user_access',
    'access arguments' => array('use custom search'),
    'type' => MENU_CALLBACK,
  );

  $items['autocomplete/sku'] = array(
    'title' => 'Sku Search',
    'page callback' => 'skusearch_autocomplete',
    'access callback' => 'user_access',
    'access arguments' => array('use custom search'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback for search/sku.
 */
function skusearch_query_sku($sku) {
  // run the apachesolr query
  $name = 'skusearch';
  $params = array(
    'q' => '',
    'fq' => array('bundle:products', 'ts_field_sku:' . check_plain($sku)),
  );

  $results = apachesolr_search_run($name, $params);

  // set default url
  $url = url('search/apachesolr_search/' . check_plain($sku), array('absolute' => TRUE));

  // if got results, pull out and return the url for the product
  if (!empty($results)) {
    $url = $results[0]['link'];
  }

  if (!empty($_POST['ajax'])) {
    drupal_json_output(array('url' => $url));
    exit();
  }

  drupal_goto($url);
}

/**
 * Menu callback for autocomplete/sku
 */
function skusearch_autocomplete($sku) {
  // run the apachesolr query
  $name = 'skusearch_autocomplete';
  $params = array(
    'q' => check_plain($sku),
    'fq' => array('bundle:products'),
    'qf' => array('ts_field_sku^50'),
  );

  $results = apachesolr_search_run($name, $params);
  $part_numbers = array();

  // pull the part numbers from the results
  if (!empty($results)) {
    foreach ($results as $result) {
      $part_numbers[] = $result['fields']['ts_field_sku'];
    }
  }

  drupal_json_output($part_numbers);
  exit();
}